import { useState, useCallback, useRef } from "react";
import { MiniToolLayout } from "@/components/layout/MiniToolLayout";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import {
  Mail, RefreshCw, Copy, Inbox, ChevronRight, ArrowLeft,
  Clock, Loader2, MailOpen, AlertCircle, Sparkles,
} from "lucide-react";

interface Message {
  mid: string;
  from?: string;
  subject?: string;
  date?: string;
}

interface MessageDetail {
  content?: string;
  from?: string;
  subject?: string;
  date?: string;
}

const faqs = [
  { q: "What is a temporary Gmail address?", a: "A temporary Gmail address is a real Gmail inbox generated on the fly that you can use for sign-ups, trials, or any situation where you don't want to give out your real email. Messages arrive in the inbox just like a normal Gmail account, but the address is disposable." },
  { q: "How long does the temp email last?", a: "Temporary emails generated by Gmailnator typically last for a limited time. Once you close the tool or the session expires, the inbox is gone. Use it only for receiving one-off verification emails or sign-up confirmations." },
  { q: "Can I receive any email with this address?", a: "Yes — the generated address is a real Gmail address, so it can receive emails from any sender. It's particularly useful for sign-up confirmations, password resets, and trial activations." },
  { q: "Is my data private?", a: "The generated inbox is temporary and not linked to your identity. However, anyone who knows the generated email address could also view its inbox. Don't use it for anything sensitive." },
  { q: "Why use a disposable email?", a: "Disposable emails protect your real inbox from spam, let you try services without committing your primary address, and are perfect for one-time verifications where you don't want to receive future marketing emails." },
];

const relatedTools = [
  { title: "Email Validator", href: "/tools/email-validator", description: "Validate email address syntax in bulk." },
  { title: "Email Username Generator", href: "/tools/email-username-generator", description: "Generate professional email address formats." },
  { title: "Email Signature Generator", href: "/tools/email-signature-generator", description: "Build a professional email signature." },
];

export default function TempGmail() {
  const [email, setEmail] = useState<string | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [selectedMessage, setSelectedMessage] = useState<MessageDetail | null>(null);
  const [selectedMid, setSelectedMid] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [fetchingMessages, setFetchingMessages] = useState(false);
  const [fetchingMessage, setFetchingMessage] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const { toast } = useToast();
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const stopPolling = () => {
    if (pollRef.current) {
      clearInterval(pollRef.current);
      pollRef.current = null;
    }
  };

  const fetchMessages = useCallback(async (addr: string, silent = false) => {
    if (!silent) setFetchingMessages(true);
    try {
      const res = await fetch("/api/temp-gmail/messages", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email: addr }),
      });
      const data = await res.json() as { messages?: Message[]; error?: string };
      if (!res.ok) {
        if (!silent) setError(data.error ?? "Failed to fetch messages.");
        return;
      }
      setMessages(data.messages ?? []);
    } catch {
      if (!silent) setError("Network error while fetching messages.");
    } finally {
      if (!silent) setFetchingMessages(false);
    }
  }, []);

  const generateEmail = async () => {
    stopPolling();
    setGenerating(true);
    setError(null);
    setEmail(null);
    setMessages([]);
    setSelectedMessage(null);
    setSelectedMid(null);

    try {
      const res = await fetch("/api/temp-gmail/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
      });
      const data = await res.json() as { email?: string; error?: string };

      if (!res.ok || !data.email) {
        setError(data.error ?? "Failed to generate email address.");
        return;
      }

      setEmail(data.email);
      await fetchMessages(data.email);

      pollRef.current = setInterval(() => {
        fetchMessages(data.email!, true);
      }, 10000);
    } catch {
      setError("Network error. Please try again.");
    } finally {
      setGenerating(false);
    }
  };

  const openMessage = async (mid: string) => {
    if (!email) return;
    setSelectedMid(mid);
    setFetchingMessage(true);
    setSelectedMessage(null);

    try {
      const res = await fetch("/api/temp-gmail/message", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, mid }),
      });
      const data = await res.json() as MessageDetail & { error?: string };
      if (!res.ok) {
        toast({ title: "Error", description: data.error ?? "Could not load message.", variant: "destructive" });
        return;
      }
      setSelectedMessage(data);
    } catch {
      toast({ title: "Error", description: "Network error loading message.", variant: "destructive" });
    } finally {
      setFetchingMessage(false);
    }
  };

  const copyEmail = () => {
    if (!email) return;
    navigator.clipboard.writeText(email);
    toast({ title: "Copied!", description: "Email address copied to clipboard." });
  };

  const refreshMessages = () => {
    if (email) fetchMessages(email);
  };

  return (
    <MiniToolLayout
      seoTitle="Temp Gmail Generator — Free Disposable Email Inbox"
      seoDescription="Generate a temporary Gmail address instantly and receive emails in the live inbox — no sign-up, no personal info required. Perfect for trials, sign-ups, and one-time verifications."
      icon={Mail}
      badge="Email Tool"
      title="Temp Gmail Generator"
      description="Generate a real, temporary Gmail inbox in one click. Use it for sign-ups, trials, or verifications without giving out your real email address."
      faqs={faqs}
      relatedTools={relatedTools}
      affiliateCategory="growth"
    >
      <div className="space-y-6">

        {/* Generate button */}
        <div className="flex flex-col items-center gap-4 py-2">
          <Button
            onClick={generateEmail}
            disabled={generating}
            size="lg"
            className="gap-2.5 px-8 h-11 text-sm font-semibold shadow-md shadow-primary/20"
          >
            {generating
              ? <><Loader2 className="h-4 w-4 animate-spin" /> Generating…</>
              : <><Sparkles className="h-4 w-4" /> {email ? "Generate New Email" : "Generate Temp Email"}</>
            }
          </Button>
          {!email && !error && (
            <p className="text-xs text-muted-foreground text-center max-w-xs">
              Generates a real Gmail address. Inbox auto-refreshes every 10 seconds.
            </p>
          )}
        </div>

        {/* Error */}
        {error && (
          <div className="flex items-start gap-3 rounded-xl border border-red-500/20 bg-red-500/5 px-4 py-3">
            <AlertCircle className="h-4 w-4 text-red-400 shrink-0 mt-0.5" />
            <p className="text-sm text-red-400">{error}</p>
          </div>
        )}

        {/* Generated email display */}
        {email && (
          <div className="rounded-xl border border-primary/20 bg-primary/5 p-4 space-y-1">
            <div className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">
              Your Temporary Email
            </div>
            <div className="flex items-center gap-3">
              <div className="flex-1 min-w-0">
                <div className="font-mono text-base font-semibold text-foreground truncate">{email}</div>
              </div>
              <Button variant="outline" size="sm" onClick={copyEmail} className="shrink-0 gap-1.5 border-border/60 h-8 text-xs">
                <Copy className="h-3.5 w-3.5" /> Copy
              </Button>
            </div>
            <div className="flex items-center gap-1.5 pt-1">
              <div className="h-1.5 w-1.5 rounded-full bg-emerald-400 animate-pulse" />
              <span className="text-[11px] text-muted-foreground">Live inbox · auto-refreshing every 10s</span>
            </div>
          </div>
        )}

        {/* Inbox */}
        {email && (
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                {selectedMessage ? (
                  <button
                    onClick={() => { setSelectedMessage(null); setSelectedMid(null); }}
                    className="flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors"
                  >
                    <ArrowLeft className="h-3.5 w-3.5" /> Back to inbox
                  </button>
                ) : (
                  <>
                    <Inbox className="h-4 w-4 text-muted-foreground" />
                    <span className="text-sm font-semibold">Inbox</span>
                    {messages.length > 0 && (
                      <span className="text-xs bg-primary/10 text-primary px-1.5 py-0.5 rounded-full font-semibold">
                        {messages.length}
                      </span>
                    )}
                  </>
                )}
              </div>
              {!selectedMessage && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={refreshMessages}
                  disabled={fetchingMessages}
                  className="h-7 text-xs gap-1.5 text-muted-foreground hover:text-foreground"
                >
                  <RefreshCw className={`h-3.5 w-3.5 ${fetchingMessages ? "animate-spin" : ""}`} />
                  Refresh
                </Button>
              )}
            </div>

            {/* Message detail view */}
            {selectedMessage && (
              <div className="rounded-xl border border-border/60 bg-card/50 overflow-hidden">
                <div className="px-4 py-3 border-b border-border/40 bg-muted/20 space-y-1">
                  <div className="text-sm font-semibold text-foreground">
                    {selectedMessage.subject ?? "(No subject)"}
                  </div>
                  <div className="flex items-center gap-4 text-xs text-muted-foreground">
                    {selectedMessage.from && <span>From: {selectedMessage.from}</span>}
                    {selectedMessage.date && (
                      <span className="flex items-center gap-1">
                        <Clock className="h-3 w-3" /> {selectedMessage.date}
                      </span>
                    )}
                  </div>
                </div>
                {fetchingMessage ? (
                  <div className="flex items-center justify-center py-10 gap-2 text-muted-foreground text-sm">
                    <Loader2 className="h-4 w-4 animate-spin" /> Loading message…
                  </div>
                ) : (
                  <div
                    className="p-4 text-sm prose prose-invert prose-sm max-w-none overflow-auto"
                    style={{ maxHeight: "400px" }}
                    dangerouslySetInnerHTML={{ __html: selectedMessage.content ?? "<p>No content</p>" }}
                  />
                )}
              </div>
            )}

            {/* Message list */}
            {!selectedMessage && (
              <>
                {fetchingMessages && messages.length === 0 && (
                  <div className="flex items-center justify-center py-10 gap-2 text-muted-foreground text-sm">
                    <Loader2 className="h-4 w-4 animate-spin" /> Checking inbox…
                  </div>
                )}

                {!fetchingMessages && messages.length === 0 && (
                  <div className="rounded-xl border border-dashed border-border/50 bg-muted/10 p-10 text-center space-y-2">
                    <MailOpen className="h-8 w-8 text-muted-foreground/30 mx-auto" />
                    <p className="text-sm text-muted-foreground/60">No messages yet</p>
                    <p className="text-xs text-muted-foreground/40">Send an email to <span className="font-mono">{email}</span> and it will appear here</p>
                  </div>
                )}

                {messages.length > 0 && (
                  <div className="rounded-xl border border-border/60 overflow-hidden divide-y divide-border/40">
                    {messages.map((msg) => (
                      <button
                        key={msg.mid}
                        onClick={() => openMessage(msg.mid)}
                        disabled={fetchingMessage && selectedMid === msg.mid}
                        className="w-full flex items-center gap-3 px-4 py-3 text-left hover:bg-muted/40 transition-colors group"
                      >
                        <Mail className="h-4 w-4 text-primary/60 shrink-0" />
                        <div className="flex-1 min-w-0">
                          <div className="text-sm font-medium text-foreground truncate">
                            {msg.subject ?? "(No subject)"}
                          </div>
                          <div className="text-xs text-muted-foreground flex items-center gap-2 mt-0.5">
                            {msg.from && <span className="truncate max-w-[200px]">{msg.from}</span>}
                            {msg.date && (
                              <span className="flex items-center gap-1 shrink-0">
                                <Clock className="h-3 w-3" /> {msg.date}
                              </span>
                            )}
                          </div>
                        </div>
                        {fetchingMessage && selectedMid === msg.mid
                          ? <Loader2 className="h-4 w-4 animate-spin text-muted-foreground shrink-0" />
                          : <ChevronRight className="h-4 w-4 text-muted-foreground/40 group-hover:text-muted-foreground shrink-0 transition-colors" />
                        }
                      </button>
                    ))}
                  </div>
                )}
              </>
            )}
          </div>
        )}
      </div>
    </MiniToolLayout>
  );
}
