import { Router } from "express";

const router = Router();

const GROQ_URL = "https://api.groq.com/openai/v1/chat/completions";
const DETECT_MODEL = "llama-3.3-70b-versatile";
const HUMANIZE_MODEL = "llama-3.3-70b-versatile";

// Read comma-separated keys from env, rotate on 429
function getGroqKeys(): string[] {
  const raw = process.env.GROQ_API_KEY ?? "";
  return raw.split(",").map(k => k.trim()).filter(Boolean);
}

async function callGroq(
  model: string,
  prompt: string,
  maxTokens: number,
  res: import("express").Response
): Promise<string | null> {
  const keys = getGroqKeys();
  if (keys.length === 0) {
    res.status(503).json({ error: "Service not configured. Please contact the administrator." });
    return null;
  }

  for (let i = 0; i < keys.length; i++) {
    const r = await fetch(GROQ_URL, {
      method: "POST",
      headers: { Authorization: `Bearer ${keys[i]}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        model,
        max_tokens: maxTokens,
        temperature: 0.1,
        messages: [{ role: "user", content: prompt }],
      }),
      signal: AbortSignal.timeout(30000),
    });

    if (r.status === 429 && i < keys.length - 1) continue; // try next key

    if (!r.ok) {
      if (r.status === 429) { res.status(429).json({ error: "Service is rate-limited. Please try again in a moment." }); return null; }
      if (r.status === 401) { res.status(503).json({ error: "Service misconfigured. Please contact the administrator." }); return null; }
      const e = (await r.json().catch(() => ({}))) as { error?: { message?: string } };
      res.status(500).json({ error: e?.error?.message ?? "Groq API error" });
      return null;
    }

    const data = (await r.json()) as { choices?: Array<{ message?: { content?: string } }> };
    return data.choices?.[0]?.message?.content ?? "";
  }

  res.status(429).json({ error: "Service is rate-limited. Please try again in a moment." });
  return null;
}

router.post("/ai-detector/detect", async (req, res) => {
  const { text } = req.body as { text?: string };

  if (!text || text.trim().length < 30) {
    res.status(400).json({ error: "Please provide at least 30 characters of text." });
    return;
  }
  if (text.length > 8000) {
    res.status(400).json({ error: "Text too long. Maximum 8000 characters." });
    return;
  }

  const prompt = `You are an expert AI text detection system. Analyze the following text and determine the probability that it was generated by an AI (such as ChatGPT, Claude, Gemini, or similar LLMs).

TEXT TO ANALYZE:
"""
${text.trim()}
"""

Analyze for these AI writing signals:
- Uniform sentence rhythm and length
- Overuse of transitional phrases (Furthermore, Moreover, In conclusion, It is worth noting, etc.)
- Absence of personal anecdotes, opinions, or lived experience
- Passive voice overuse
- Hedging language (it is important to note, it should be mentioned, etc.)
- Overly balanced, on-the-other-hand structure
- Lack of typos, hesitations, or natural human quirks
- Generic and safe phrasing with no strong voice
- Repetitive vocabulary and concepts
- Perfect grammar throughout

Return ONLY valid JSON (no markdown, no explanation), exactly in this format:
{
  "score": <integer 0-100, where 100 = definitely AI>,
  "label": "<one of: 'Likely Human', 'Possibly Human', 'Mixed / Uncertain', 'Possibly AI', 'Likely AI-Generated'>",
  "confidence": "<one of: 'low', 'medium', 'high'>",
  "summary": "<2-3 sentence plain-English explanation of why you gave this score>",
  "indicators": ["<up to 5 specific signals found in the text>"],
  "sentences": [
    { "text": "<first 80 chars of sentence>", "score": <0-100> }
  ]
}

Include up to 12 sentences in the sentences array. Score each sentence individually for AI probability.`;

  try {
    const raw = await callGroq(DETECT_MODEL, prompt, 1200, res);
    if (raw === null) return;

    let parsed: unknown;
    try {
      const jsonMatch = raw.match(/\{[\s\S]*\}/);
      parsed = JSON.parse(jsonMatch?.[0] ?? raw);
    } catch {
      res.status(500).json({ error: "Failed to parse detection result. Please try again." });
      return;
    }

    res.json(parsed);
  } catch (err) {
    req.log.error({ err }, "ai-detector detect failed");
    res.status(500).json({ error: "Detection failed. Please try again." });
  }
});

router.post("/ai-detector/humanize", async (req, res) => {
  const { text, style } = req.body as { text?: string; style?: string };

  if (!text || text.trim().length < 30) {
    res.status(400).json({ error: "Please provide at least 30 characters of text." });
    return;
  }
  if (text.length > 6000) {
    res.status(400).json({ error: "Text too long for humanization. Maximum 6000 characters." });
    return;
  }

  const styleGuide: Record<string, string> = {
    casual:       "casual and conversational — like texting a smart friend. Short sentences. Contractions everywhere. Relatable.",
    professional: "professional but warm — clear, direct, human. No corporate jargon. Sounds like a confident expert talking, not a press release.",
    academic:     "academic but readable — precise and structured, but with a real voice. Avoid passive voice. Sound like a sharp human researcher.",
    creative:     "creative and expressive — vivid, personal, with rhythm. Mix short punchy lines with longer flowing ones.",
  };

  const tone = styleGuide[style ?? "casual"] ?? styleGuide.casual;

  const prompt = `You are an expert text humanizer. Your job is to rewrite AI-generated text so it reads as if written by a real human.

TARGET STYLE: ${tone}

RULES — strictly follow all of these:
1. Use contractions naturally (don't, it's, you'll, they're, I've, etc.)
2. Vary sentence length dramatically — mix very short sentences with longer ones
3. Remove all AI transition phrases: "Furthermore", "Moreover", "In conclusion", "It is worth noting", "It should be noted", "In today's world", "In the realm of", "Delve into", "It is important to", "It is essential to"
4. Add natural imperfections: start sentences with "And", "But", "So", or "Because" occasionally
5. Use active voice, not passive voice
6. Remove hedging: replace "it is important to note that" with direct statements
7. Add personality — a brief personal angle, mild opinion, or concrete example where it fits
8. Keep all the original facts and core meaning intact
9. Do NOT add new information or change facts
10. Do NOT use bullet points or numbered lists unless the original had them
11. Do NOT explain what you're doing — just output the rewritten text

ORIGINAL TEXT:
"""
${text.trim()}
"""

Output ONLY the rewritten text. Nothing else. No preamble, no explanation, no quotes around it.`;

  try {
    const result = await callGroq(HUMANIZE_MODEL, prompt, 2000, res);
    if (result === null) return;

    res.json({ humanized: result.trim() });
  } catch (err) {
    req.log.error({ err }, "ai-detector humanize failed");
    res.status(500).json({ error: "Humanization failed. Please try again." });
  }
});

export default router;
